/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GesMED.bsi.Interface;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Leoncio Carioca
 */
public class AgendarConsulta extends javax.swing.JFrame {
    
    private PainelPrincipal Pai;

    /**
     * Creates new form AgendarConsulta
     */
    public AgendarConsulta() {
        initComponents();

    }
    public AgendarConsulta(PainelPrincipal Principal) {
        Pai = Principal;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFinanceiro = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        pCabecalho = new javax.swing.JPanel();
        imgTituloJanela = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_Close = new javax.swing.JLabel();
        btn_Maximizar = new javax.swing.JLabel();
        btn_Minimizar = new javax.swing.JLabel();
        pCentral = new javax.swing.JPanel();
        pAgendamento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfdNome = new javax.swing.JTextField();
        lbConvenio = new javax.swing.JLabel();
        jcbConvenio = new javax.swing.JComboBox<>();
        jcbStatus = new javax.swing.JComboBox<>();
        lbStatus = new javax.swing.JLabel();
        lbProcedimento = new javax.swing.JLabel();
        jcbProcedimento = new javax.swing.JComboBox<>();
        lbDataAgenda = new javax.swing.JLabel();
        tfdDataAgenda = new javax.swing.JFormattedTextField();
        lbDas = new javax.swing.JLabel();
        lbHorarioAgenda = new javax.swing.JLabel();
        lbAs = new javax.swing.JLabel();
        lbObsersavacoes = new javax.swing.JLabel();
        jScrollPaneObservacoes = new javax.swing.JScrollPane();
        textObservacoes = new javax.swing.JTextArea();
        lbNome = new javax.swing.JLabel();
        tfdDas = new javax.swing.JFormattedTextField();
        tfdAs = new javax.swing.JFormattedTextField();
        lbCPF = new javax.swing.JLabel();
        tfdCPF = new javax.swing.JFormattedTextField();
        pFinanceiro = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lbDataLancamento = new javax.swing.JLabel();
        lbValorAtendimento = new javax.swing.JLabel();
        lbPagoEm = new javax.swing.JLabel();
        jCheckJaPago = new javax.swing.JCheckBox();
        lbFormaPagamento = new javax.swing.JLabel();
        tfdAtendimento = new javax.swing.JTextField();
        tfdPagoEm = new javax.swing.JFormattedTextField();
        tfdDataLancamento = new javax.swing.JFormattedTextField();
        jcbFormaPagamento = new javax.swing.JComboBox<>();
        btn_Salvar = new javax.swing.JButton();
        btn_Sair = new javax.swing.JButton();
        jScrollPaneObservacoes1 = new javax.swing.JScrollPane();
        textObservacoes1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(0, 204, 204));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pCabecalho.setBackground(new java.awt.Color(0, 164, 137));

        imgTituloJanela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufac/bsi/images/Agenda_60px.png"))); // NOI18N
        imgTituloJanela.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Agendar");

        btn_Close.setBackground(new java.awt.Color(0, 164, 137));
        btn_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufac/bsi/images/Close Window_36px.png"))); // NOI18N
        btn_Close.setOpaque(true);
        btn_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CloseMouseExited(evt);
            }
        });

        btn_Maximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufac/bsi/images/Restore Window_36px.png"))); // NOI18N

        btn_Minimizar.setBackground(new java.awt.Color(0, 164, 137));
        btn_Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufac/bsi/images/Minimize Window_36px.png"))); // NOI18N
        btn_Minimizar.setOpaque(true);
        btn_Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_MinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_MinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_MinimizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pCabecalhoLayout = new javax.swing.GroupLayout(pCabecalho);
        pCabecalho.setLayout(pCabecalhoLayout);
        pCabecalhoLayout.setHorizontalGroup(
            pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCabecalhoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(imgTituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 527, Short.MAX_VALUE)
                .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Minimizar)
                    .addGroup(pCabecalhoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btn_Maximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(btn_Close))
        );
        pCabecalhoLayout.setVerticalGroup(
            pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imgTituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(pCabecalhoLayout.createSequentialGroup()
                .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Maximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        bg.add(pCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 110));

        pCentral.setBackground(new java.awt.Color(255, 255, 255));
        pCentral.setLayout(new java.awt.CardLayout());

        pAgendamento.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setOpaque(true);

        lbConvenio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbConvenio.setText("Convênio:");

        jcbConvenio.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jcbConvenio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Particular" }));

        jcbStatus.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Agendado", "Confirmado", "Chegou", "Em Andamento", "Finalizando", "Cancelado", "Faltou", " ", " ", " " }));

        lbStatus.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbStatus.setText("Status:");

        lbProcedimento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbProcedimento.setText("Procedimento:");

        jcbProcedimento.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jcbProcedimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Consulta", "Retorno", " " }));

        lbDataAgenda.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbDataAgenda.setText("Data:");

        try {
            tfdDataAgenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbDas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbDas.setText("das:");

        lbHorarioAgenda.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbHorarioAgenda.setText("Horário");

        lbAs.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbAs.setText("às:");

        lbObsersavacoes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbObsersavacoes.setText("Observações:");

        textObservacoes.setColumns(20);
        textObservacoes.setRows(5);
        jScrollPaneObservacoes.setViewportView(textObservacoes);

        lbNome.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbNome.setText("Nome:");

        lbCPF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbCPF.setText("CPF:");

        try {
            tfdCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout pAgendamentoLayout = new javax.swing.GroupLayout(pAgendamento);
        pAgendamento.setLayout(pAgendamentoLayout);
        pAgendamentoLayout.setHorizontalGroup(
            pAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pAgendamentoLayout.createSequentialGroup()
                .addGroup(pAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAgendamentoLayout.createSequentialGroup()
                        .addGroup(pAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pAgendamentoLayout.createSequentialGroup()
                                .addGroup(pAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pAgendamentoLayout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(pAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pAgendamentoLayout.createSequentialGroup()
                                                .addGap(244, 244, 244)
                                                .addComponent(lbHorarioAgenda))
                                            .addComponent(lbDataAgenda)))
                                    .addGroup(pAgendamentoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lbProcedimento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfdDataAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcbProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcbConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbDas)
                                .addGap(18, 18, 18)
                                .addComponent(tfdDas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAgendamentoLayout.createSequentialGroup()
                                .addGap(0, 52, Short.MAX_VALUE)
                                .addComponent(lbConvenio)
                                .addGap(325, 325, 325)
                                .addComponent(lbStatus)
                                .addGap(84, 84, 84)))
                        .addComponent(lbAs, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdAs, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pAgendamentoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pAgendamentoLayout.createSequentialGroup()
                                .addComponent(lbObsersavacoes)
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPaneObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))))
                    .addGroup(pAgendamentoLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(pAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCPF)
                            .addComponent(lbNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        pAgendamentoLayout.setVerticalGroup(
            pAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAgendamentoLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(pAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConvenio)
                    .addComponent(jcbConvenio, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lbStatus)
                    .addComponent(jcbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProcedimento)
                    .addComponent(jcbProcedimento, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(pAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdDataAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHorarioAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAs, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdDas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdAs, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbObsersavacoes)
                    .addComponent(jScrollPaneObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        pCentral.add(pAgendamento, "cardAgendamento");

        pFinanceiro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setBackground(new java.awt.Color(0, 204, 204));
        jLabel13.setOpaque(true);

        lbDataLancamento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbDataLancamento.setText("Data do Lançamento:");

        lbValorAtendimento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbValorAtendimento.setText("Valor do Atendimento:");

        lbPagoEm.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbPagoEm.setText("Pago em:");

        jCheckJaPago.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckJaPago.setText("Já Pago?");

        lbFormaPagamento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbFormaPagamento.setText("Forma de Pagamento:");

        try {
            tfdPagoEm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfdDataLancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jcbFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Dinheiro", "Cartão de Crédito", "Cartão de Débito", "Cheque", "Transferência Bancária", "Convênio" }));

        javax.swing.GroupLayout pFinanceiroLayout = new javax.swing.GroupLayout(pFinanceiro);
        pFinanceiro.setLayout(pFinanceiroLayout);
        pFinanceiroLayout.setHorizontalGroup(
            pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
            .addGroup(pFinanceiroLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckJaPago)
                    .addGroup(pFinanceiroLayout.createSequentialGroup()
                        .addComponent(lbValorAtendimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pFinanceiroLayout.createSequentialGroup()
                        .addComponent(lbPagoEm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdPagoEm, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbDataLancamento)
                    .addComponent(lbFormaPagamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pFinanceiroLayout.setVerticalGroup(
            pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFinanceiroLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValorAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jCheckJaPago)
                .addGap(18, 18, 18)
                .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfdPagoEm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbPagoEm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 123, Short.MAX_VALUE))
        );

        pCentral.add(pFinanceiro, "cardFinanceiro");

        bg.add(pCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 810, 440));

        btn_Salvar.setBackground(new java.awt.Color(255, 255, 255));
        btn_Salvar.setText("SALVAR");
        bg.add(btn_Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 70, 30));

        btn_Sair.setBackground(new java.awt.Color(255, 255, 255));
        btn_Sair.setText("SAIR");
        btn_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SairActionPerformed(evt);
            }
        });
        bg.add(btn_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 70, 30));

        textObservacoes1.setColumns(20);
        textObservacoes1.setRows(5);
        jScrollPaneObservacoes1.setViewportView(textObservacoes1);

        bg.add(jScrollPaneObservacoes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CloseMouseClicked
        Pai.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CloseMouseClicked

    private void btn_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CloseMouseEntered
        btn_Close.setBackground(new Color(215, 121, 121));
    }//GEN-LAST:event_btn_CloseMouseEntered

    private void btn_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CloseMouseExited
        btn_Close.setBackground(new Color(0,164,137));
    }//GEN-LAST:event_btn_CloseMouseExited

    private void btn_MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MinimizarMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btn_MinimizarMouseClicked

    private void btn_MinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MinimizarMouseEntered
        btn_Minimizar.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btn_MinimizarMouseEntered

    private void btn_MinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MinimizarMouseExited
        btn_Minimizar.setBackground(new Color(0,164,137));
    }//GEN-LAST:event_btn_MinimizarMouseExited

    private void btn_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SairActionPerformed
        Pai.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_SairActionPerformed

    
    public void setColorClicked(JLabel lbButton){
        lbButton.setBackground(new Color(0,204,204));
    }
    
    public void setColorEntered(JLabel lbButton){
        lbButton.setBackground(new Color(200,240,240));
    }
    
    public void setColorExited(JLabel lbButton){
        lbButton.setBackground(new Color(0,204,153));
    }
    
    public void setColorPressed(JLabel lbButton){
        lbButton.setBackground(new Color(140,198,198));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendarConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.ButtonGroup bgFinanceiro;
    private javax.swing.JLabel btn_Close;
    private javax.swing.JLabel btn_Maximizar;
    private javax.swing.JLabel btn_Minimizar;
    private javax.swing.JButton btn_Sair;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JLabel imgTituloJanela;
    private javax.swing.JCheckBox jCheckJaPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPaneObservacoes;
    private javax.swing.JScrollPane jScrollPaneObservacoes1;
    private javax.swing.JComboBox<String> jcbConvenio;
    private javax.swing.JComboBox<String> jcbFormaPagamento;
    private javax.swing.JComboBox<String> jcbProcedimento;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JLabel lbAs;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbConvenio;
    private javax.swing.JLabel lbDas;
    private javax.swing.JLabel lbDataAgenda;
    private javax.swing.JLabel lbDataLancamento;
    private javax.swing.JLabel lbFormaPagamento;
    private javax.swing.JLabel lbHorarioAgenda;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbObsersavacoes;
    private javax.swing.JLabel lbPagoEm;
    private javax.swing.JLabel lbProcedimento;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbValorAtendimento;
    private javax.swing.JPanel pAgendamento;
    private javax.swing.JPanel pCabecalho;
    private javax.swing.JPanel pCentral;
    private javax.swing.JPanel pFinanceiro;
    private javax.swing.JTextArea textObservacoes;
    private javax.swing.JTextArea textObservacoes1;
    private javax.swing.JFormattedTextField tfdAs;
    private javax.swing.JTextField tfdAtendimento;
    private javax.swing.JFormattedTextField tfdCPF;
    private javax.swing.JFormattedTextField tfdDas;
    private javax.swing.JFormattedTextField tfdDataAgenda;
    private javax.swing.JFormattedTextField tfdDataLancamento;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JFormattedTextField tfdPagoEm;
    // End of variables declaration//GEN-END:variables
}
