/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GesMED.bsi.Interface;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;

//IMPORTES PARA GERAR ATESTADO
import java.io.FileOutputStream;
import java.io.IOException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.time.LocalDate;


public class AtendimentoMedico extends javax.swing.JFrame {
    
    private PainelPrincipal Pai;
    private String StatusMenu;
    /**
     * Creates new form AgendarConsulta
     */
    public AtendimentoMedico() {
        initComponents();
        StatusMenu="Anamnese";
        setColorClicked(btn_Anamnese);
    }
    public AtendimentoMedico(PainelPrincipal Principal) {
        Pai = Principal;
        initComponents();
        StatusMenu="Anamnese";
        setColorClicked(btn_Anamnese);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFinanceiro = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        pCabecalho = new javax.swing.JPanel();
        btn_Anamnese = new javax.swing.JLabel();
        btn_Financeiro = new javax.swing.JLabel();
        imgTituloJanela = new javax.swing.JLabel();
        lbIMGAtendimento = new javax.swing.JLabel();
        btn_Close = new javax.swing.JLabel();
        btn_Maximizar = new javax.swing.JLabel();
        btn_Minimizar = new javax.swing.JLabel();
        btn_Dignostico = new javax.swing.JLabel();
        pCentral = new javax.swing.JPanel();
        pAnamnese = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfdQueixaPrincipal = new javax.swing.JTextField();
        lbObsersavacoes = new javax.swing.JLabel();
        jScrollPaneObservacoes = new javax.swing.JScrollPane();
        textObservacoes = new javax.swing.JTextArea();
        lbQueixaPrincipal = new javax.swing.JLabel();
        pFinanceiro = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lbDataLancamento = new javax.swing.JLabel();
        lbValorAtendimento = new javax.swing.JLabel();
        lbPagoEm = new javax.swing.JLabel();
        jCheckJaPago = new javax.swing.JCheckBox();
        lbFormaPagamento = new javax.swing.JLabel();
        tfdAtendimento = new javax.swing.JTextField();
        tfdPagoEm = new javax.swing.JFormattedTextField();
        tfdDataLancamento = new javax.swing.JFormattedTextField();
        jcbFormaPagamento = new javax.swing.JComboBox<>();
        pDiagnostico = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfdDiagnostico = new javax.swing.JTextField();
        lbObsersavacoes1 = new javax.swing.JLabel();
        jScrollPaneObservacoes2 = new javax.swing.JScrollPane();
        textObservacoes2 = new javax.swing.JTextArea();
        lbDignostico = new javax.swing.JLabel();
        btn_Salvar = new javax.swing.JButton();
        btn_Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(0, 204, 204));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pCabecalho.setBackground(new java.awt.Color(0, 164, 137));

        btn_Anamnese.setBackground(new java.awt.Color(0, 204, 153));
        btn_Anamnese.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_Anamnese.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Anamnese.setText("Anamnese");
        btn_Anamnese.setOpaque(true);
        btn_Anamnese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_AnamneseMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AnamneseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AnamneseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AnamneseMouseEntered(evt);
            }
        });

        btn_Financeiro.setBackground(new java.awt.Color(0, 204, 153));
        btn_Financeiro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_Financeiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Financeiro.setText("Financeiro");
        btn_Financeiro.setOpaque(true);
        btn_Financeiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_FinanceiroMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_FinanceiroMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_FinanceiroMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_FinanceiroMouseEntered(evt);
            }
        });

        imgTituloJanela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufac/bsi/images/Agenda_60px.png"))); // NOI18N

        lbIMGAtendimento.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbIMGAtendimento.setForeground(new java.awt.Color(255, 255, 255));
        lbIMGAtendimento.setText("Atendimento Clínico");

        btn_Close.setBackground(new java.awt.Color(0, 164, 137));
        btn_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufac/bsi/images/Close Window_36px.png"))); // NOI18N
        btn_Close.setOpaque(true);
        btn_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CloseMouseExited(evt);
            }
        });

        btn_Maximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufac/bsi/images/Restore Window_36px.png"))); // NOI18N

        btn_Minimizar.setBackground(new java.awt.Color(0, 164, 137));
        btn_Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufac/bsi/images/Minimize Window_36px.png"))); // NOI18N
        btn_Minimizar.setOpaque(true);
        btn_Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_MinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_MinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_MinimizarMouseExited(evt);
            }
        });

        btn_Dignostico.setBackground(new java.awt.Color(0, 204, 153));
        btn_Dignostico.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_Dignostico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Dignostico.setText("Diagnóstico");
        btn_Dignostico.setOpaque(true);
        btn_Dignostico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_DignosticoMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DignosticoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DignosticoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_DignosticoMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pCabecalhoLayout = new javax.swing.GroupLayout(pCabecalho);
        pCabecalho.setLayout(pCabecalhoLayout);
        pCabecalhoLayout.setHorizontalGroup(
            pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCabecalhoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(imgTituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCabecalhoLayout.createSequentialGroup()
                        .addComponent(lbIMGAtendimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Minimizar)
                            .addGroup(pCabecalhoLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btn_Maximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)
                        .addComponent(btn_Close))
                    .addGroup(pCabecalhoLayout.createSequentialGroup()
                        .addComponent(btn_Anamnese, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Dignostico, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Financeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(161, Short.MAX_VALUE))))
        );
        pCabecalhoLayout.setVerticalGroup(
            pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCabecalhoLayout.createSequentialGroup()
                .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCabecalhoLayout.createSequentialGroup()
                        .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Maximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pCabecalhoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pCabecalhoLayout.createSequentialGroup()
                                .addComponent(imgTituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lbIMGAtendimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Anamnese, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Financeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Dignostico, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        bg.add(pCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 110));

        pCentral.setBackground(new java.awt.Color(255, 255, 255));
        pCentral.setLayout(new java.awt.CardLayout());

        pAnamnese.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setOpaque(true);

        lbObsersavacoes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbObsersavacoes.setText("Observações:");

        textObservacoes.setColumns(20);
        textObservacoes.setRows(5);
        jScrollPaneObservacoes.setViewportView(textObservacoes);

        lbQueixaPrincipal.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbQueixaPrincipal.setText("Queixa Principal:");

        javax.swing.GroupLayout pAnamneseLayout = new javax.swing.GroupLayout(pAnamnese);
        pAnamnese.setLayout(pAnamneseLayout);
        pAnamneseLayout.setHorizontalGroup(
            pAnamneseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pAnamneseLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(pAnamneseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pAnamneseLayout.createSequentialGroup()
                        .addComponent(lbQueixaPrincipal)
                        .addGap(18, 18, 18)
                        .addComponent(tfdQueixaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pAnamneseLayout.createSequentialGroup()
                        .addComponent(lbObsersavacoes)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        pAnamneseLayout.setVerticalGroup(
            pAnamneseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAnamneseLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(pAnamneseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdQueixaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQueixaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pAnamneseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbObsersavacoes)
                    .addComponent(jScrollPaneObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pCentral.add(pAnamnese, "Anamnese");

        pFinanceiro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setBackground(new java.awt.Color(0, 204, 204));
        jLabel13.setOpaque(true);

        lbDataLancamento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbDataLancamento.setText("Data do Lançamento:");

        lbValorAtendimento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbValorAtendimento.setText("Valor do Atendimento:");

        lbPagoEm.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbPagoEm.setText("Pago em:");

        jCheckJaPago.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckJaPago.setText("Já Pago?");

        lbFormaPagamento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbFormaPagamento.setText("Forma de Pagamento:");

        try {
            tfdPagoEm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfdDataLancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jcbFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Dinheiro", "Cartão de Crédito", "Cartão de Débito", "Cheque", "Transferência Bancária", "Convênio" }));

        javax.swing.GroupLayout pFinanceiroLayout = new javax.swing.GroupLayout(pFinanceiro);
        pFinanceiro.setLayout(pFinanceiroLayout);
        pFinanceiroLayout.setHorizontalGroup(
            pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
            .addGroup(pFinanceiroLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckJaPago)
                    .addGroup(pFinanceiroLayout.createSequentialGroup()
                        .addComponent(lbValorAtendimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pFinanceiroLayout.createSequentialGroup()
                        .addComponent(lbPagoEm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdPagoEm, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbDataLancamento)
                    .addComponent(lbFormaPagamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pFinanceiroLayout.setVerticalGroup(
            pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFinanceiroLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValorAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jCheckJaPago)
                .addGap(18, 18, 18)
                .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfdPagoEm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbPagoEm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 123, Short.MAX_VALUE))
        );

        pCentral.add(pFinanceiro, "Financeiro");

        pDiagnostico.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setOpaque(true);

        lbObsersavacoes1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbObsersavacoes1.setText("Descrição:");

        textObservacoes2.setColumns(20);
        textObservacoes2.setRows(5);
        jScrollPaneObservacoes2.setViewportView(textObservacoes2);

        lbDignostico.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbDignostico.setText("Diagnóstico:");

        javax.swing.GroupLayout pDiagnosticoLayout = new javax.swing.GroupLayout(pDiagnostico);
        pDiagnostico.setLayout(pDiagnosticoLayout);
        pDiagnosticoLayout.setHorizontalGroup(
            pDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pDiagnosticoLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(pDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbObsersavacoes1)
                    .addComponent(lbDignostico))
                .addGap(18, 18, 18)
                .addGroup(pDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfdDiagnostico)
                    .addComponent(jScrollPaneObservacoes2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        pDiagnosticoLayout.setVerticalGroup(
            pDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDiagnosticoLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(pDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDignostico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbObsersavacoes1)
                    .addComponent(jScrollPaneObservacoes2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pCentral.add(pDiagnostico, "Diagnostico");

        bg.add(pCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 810, 440));

        btn_Salvar.setBackground(new java.awt.Color(255, 255, 255));
        btn_Salvar.setText("SALVAR");
        bg.add(btn_Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 90, 30));

        btn_Sair.setBackground(new java.awt.Color(255, 255, 255));
        btn_Sair.setText("SAIR");
        btn_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SairActionPerformed(evt);
            }
        });
        bg.add(btn_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AnamneseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AnamneseMouseClicked
        setColorClicked(btn_Anamnese);
        setColorExited(btn_Financeiro);
        setColorExited(btn_Dignostico);
        StatusMenu = "Anamnese";
        CardLayout cl = (CardLayout) pCentral.getLayout();
        cl.show(pCentral, "Anamnese");
    }//GEN-LAST:event_btn_AnamneseMouseClicked

    private void btn_FinanceiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FinanceiroMouseClicked
        
        btn_Financeiro.setText("Financeiro");
        setColorClicked(btn_Financeiro);
        setColorExited(btn_Anamnese);
        setColorExited(btn_Dignostico);
        StatusMenu = "Financeiro";
        CardLayout cl = (CardLayout) pCentral.getLayout();
        cl.show(pCentral, "Financeiro");
        
    }//GEN-LAST:event_btn_FinanceiroMouseClicked

    private void btn_AnamneseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AnamneseMouseEntered
        if(!StatusMenu.equals("Anamnese"))
        setColorEntered(btn_Anamnese);
    }//GEN-LAST:event_btn_AnamneseMouseEntered

    private void btn_FinanceiroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FinanceiroMouseEntered
        if(!StatusMenu.equals("Financeiro")){
          setColorEntered(btn_Financeiro);
        }
    }//GEN-LAST:event_btn_FinanceiroMouseEntered

    private void btn_AnamneseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AnamneseMouseExited
        if(!StatusMenu.equals("Anamnese"))
        setColorExited(btn_Anamnese);
    }//GEN-LAST:event_btn_AnamneseMouseExited

    private void btn_FinanceiroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FinanceiroMouseExited
        if(!StatusMenu.equals("Financeiro"))
        setColorExited(btn_Financeiro);
    }//GEN-LAST:event_btn_FinanceiroMouseExited

    private void btn_AnamneseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AnamneseMousePressed
        setColorPressed(btn_Anamnese);
    }//GEN-LAST:event_btn_AnamneseMousePressed

    private void btn_FinanceiroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FinanceiroMousePressed
        setColorPressed(btn_Financeiro);
    }//GEN-LAST:event_btn_FinanceiroMousePressed

    private void btn_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CloseMouseClicked
        Pai.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CloseMouseClicked

    private void btn_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CloseMouseEntered
        btn_Close.setBackground(new Color(215, 121, 121));
    }//GEN-LAST:event_btn_CloseMouseEntered

    private void btn_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CloseMouseExited
        btn_Close.setBackground(new Color(0,164,137));
    }//GEN-LAST:event_btn_CloseMouseExited

    private void btn_MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MinimizarMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btn_MinimizarMouseClicked

    private void btn_MinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MinimizarMouseEntered
        btn_Minimizar.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btn_MinimizarMouseEntered

    private void btn_MinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MinimizarMouseExited
        btn_Minimizar.setBackground(new Color(0,164,137));
    }//GEN-LAST:event_btn_MinimizarMouseExited

    private void btn_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SairActionPerformed
        Pai.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_SairActionPerformed

    private void btn_DignosticoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DignosticoMousePressed
        setColorPressed(btn_Dignostico);
    }//GEN-LAST:event_btn_DignosticoMousePressed

    private void btn_DignosticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DignosticoMouseClicked
        setColorClicked(btn_Dignostico);
        setColorExited(btn_Anamnese);
        setColorExited(btn_Financeiro);
        StatusMenu = "Diagnostico";
        CardLayout cl = (CardLayout) pCentral.getLayout();
        cl.show(pCentral, "Diagnostico");
    }//GEN-LAST:event_btn_DignosticoMouseClicked

    private void btn_DignosticoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DignosticoMouseExited
        if(!StatusMenu.equals("Diagnostico"))
        setColorExited(btn_Dignostico);
    }//GEN-LAST:event_btn_DignosticoMouseExited

    private void btn_DignosticoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DignosticoMouseEntered
        if(!StatusMenu.equals("Dignostico")){
          setColorEntered(btn_Dignostico);
        }
    }//GEN-LAST:event_btn_DignosticoMouseEntered
    public void EnableButton(){
        btn_Financeiro.setText("Financeiro");
        setColorExited(btn_Financeiro);
    }
    
    public void DisableButton(){
        btn_Financeiro.setText("");
        btn_Financeiro.setBackground(new Color(0,164,137));
    }
    
    public void setColorClicked(JLabel lbButton){
        lbButton.setBackground(new Color(0,204,204));
    }
    
    public void setColorEntered(JLabel lbButton){
        lbButton.setBackground(new Color(200,240,240));
    }
    
    public void setColorExited(JLabel lbButton){
        lbButton.setBackground(new Color(0,204,153));
    }
    
    public void setColorPressed(JLabel lbButton){
        lbButton.setBackground(new Color(140,198,198));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtendimentoMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtendimentoMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtendimentoMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtendimentoMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtendimentoMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.ButtonGroup bgFinanceiro;
    private javax.swing.JLabel btn_Anamnese;
    private javax.swing.JLabel btn_Close;
    private javax.swing.JLabel btn_Dignostico;
    private javax.swing.JLabel btn_Financeiro;
    private javax.swing.JLabel btn_Maximizar;
    private javax.swing.JLabel btn_Minimizar;
    private javax.swing.JButton btn_Sair;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JLabel imgTituloJanela;
    private javax.swing.JCheckBox jCheckJaPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPaneObservacoes;
    private javax.swing.JScrollPane jScrollPaneObservacoes2;
    private javax.swing.JComboBox<String> jcbFormaPagamento;
    private javax.swing.JLabel lbDataLancamento;
    private javax.swing.JLabel lbDignostico;
    private javax.swing.JLabel lbFormaPagamento;
    private javax.swing.JLabel lbIMGAtendimento;
    private javax.swing.JLabel lbObsersavacoes;
    private javax.swing.JLabel lbObsersavacoes1;
    private javax.swing.JLabel lbPagoEm;
    private javax.swing.JLabel lbQueixaPrincipal;
    private javax.swing.JLabel lbValorAtendimento;
    private javax.swing.JPanel pAnamnese;
    private javax.swing.JPanel pCabecalho;
    private javax.swing.JPanel pCentral;
    private javax.swing.JPanel pDiagnostico;
    private javax.swing.JPanel pFinanceiro;
    private javax.swing.JTextArea textObservacoes;
    private javax.swing.JTextArea textObservacoes2;
    private javax.swing.JTextField tfdAtendimento;
    private javax.swing.JFormattedTextField tfdDataLancamento;
    private javax.swing.JTextField tfdDiagnostico;
    private javax.swing.JFormattedTextField tfdPagoEm;
    private javax.swing.JTextField tfdQueixaPrincipal;
    // End of variables declaration//GEN-END:variables
}
