/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GesMED.bsi.Interface;

import GesMED.bsi.Entidades.Favorecido;


import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import GesMED.bsi.Entidades.Paciente;
import GesMED.bsi.Repositorios.ContaPacienteRepositorio;
import GesMED.bsi.Repositorios.FavorecidoRepositorio;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LancarContaPaciente extends javax.swing.JFrame {
    
    private PainelPrincipal Pai;
    private String StatusMenu;
    private Paciente paciente;
    private List<String> listaFavorecidos;
    private List<Favorecido> listFavorecido;
    /**
     * Creates new form AgendarConsulta
     */
    public LancarContaPaciente() {
        initComponents();
        DisableCheckButton();
        atualizarComboBox();

//        setColorClicked(btn_Consulta);
    }
    public LancarContaPaciente(PainelPrincipal Principal, Paciente p) {
        Pai = Principal;
        initComponents();
        this.paciente=p;
        DisableCheckButton();
        setLabelNomePaciente();
//        setColorClicked(btn_Consulta);
        atualizarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFinanceiro = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        pCabecalho = new javax.swing.JPanel();
        imgTituloJanela = new javax.swing.JLabel();
        lbIMGAtendimento = new javax.swing.JLabel();
        btn_Close = new javax.swing.JLabel();
        btn_Maximizar = new javax.swing.JLabel();
        btn_Minimizar = new javax.swing.JLabel();
        pCentral = new javax.swing.JPanel();
        pFinanceiro = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lbDataLancamento = new javax.swing.JLabel();
        lbValorAtendimento = new javax.swing.JLabel();
        lbPagoEm = new javax.swing.JLabel();
        jCheckJaPago = new javax.swing.JCheckBox();
        tfdValorAtendimento = new javax.swing.JTextField();
        lbDataLancamento1 = new javax.swing.JLabel();
        lbPaciente = new javax.swing.JLabel();
        lbNomePaciente = new javax.swing.JLabel();
        lbDataLancamento2 = new javax.swing.JLabel();
        jcbFavorecidos = new javax.swing.JComboBox<>();
        btnNovoFavorecido = new javax.swing.JButton();
        tfdDataLancamento = new datechooser.beans.DateChooserCombo();
        tfdDataVencimento = new datechooser.beans.DateChooserCombo();
        tfdDataPagamento = new datechooser.beans.DateChooserCombo();
        btn_Salvar = new javax.swing.JButton();
        btn_Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(0, 204, 204));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pCabecalho.setBackground(new java.awt.Color(0, 164, 137));

        imgTituloJanela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufac/bsi/images/Agenda_60px.png"))); // NOI18N

        lbIMGAtendimento.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbIMGAtendimento.setForeground(new java.awt.Color(255, 255, 255));
        lbIMGAtendimento.setText("Conta do Paciente");

        btn_Close.setBackground(new java.awt.Color(0, 164, 137));
        btn_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufac/bsi/images/Close Window_36px.png"))); // NOI18N
        btn_Close.setOpaque(true);
        btn_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CloseMouseExited(evt);
            }
        });

        btn_Maximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufac/bsi/images/Restore Window_36px.png"))); // NOI18N

        btn_Minimizar.setBackground(new java.awt.Color(0, 164, 137));
        btn_Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufac/bsi/images/Minimize Window_36px.png"))); // NOI18N
        btn_Minimizar.setOpaque(true);
        btn_Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_MinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_MinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_MinimizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pCabecalhoLayout = new javax.swing.GroupLayout(pCabecalho);
        pCabecalho.setLayout(pCabecalhoLayout);
        pCabecalhoLayout.setHorizontalGroup(
            pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCabecalhoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(imgTituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCabecalhoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Minimizar)
                            .addGroup(pCabecalhoLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btn_Maximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)
                        .addComponent(btn_Close))
                    .addGroup(pCabecalhoLayout.createSequentialGroup()
                        .addComponent(lbIMGAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 467, Short.MAX_VALUE))))
        );
        pCabecalhoLayout.setVerticalGroup(
            pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCabecalhoLayout.createSequentialGroup()
                .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgTituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pCabecalhoLayout.createSequentialGroup()
                        .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Maximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(lbIMGAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        bg.add(pCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 110));

        pCentral.setBackground(new java.awt.Color(255, 255, 255));
        pCentral.setLayout(new java.awt.CardLayout());

        pFinanceiro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setBackground(new java.awt.Color(0, 204, 204));
        jLabel13.setOpaque(true);

        lbDataLancamento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbDataLancamento.setText("Data do Lançamento:");

        lbValorAtendimento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbValorAtendimento.setText("Valor do Atendimento:");

        lbPagoEm.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbPagoEm.setText("Pago em:");

        jCheckJaPago.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckJaPago.setText("Já Pago?");
        jCheckJaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckJaPagoActionPerformed(evt);
            }
        });

        lbDataLancamento1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbDataLancamento1.setText("Data do Vencimento:");

        lbPaciente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbPaciente.setText("Paciente:");

        lbNomePaciente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbNomePaciente.setText("Paciente");

        lbDataLancamento2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbDataLancamento2.setText("Favorecido:");

        jcbFavorecidos.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jcbFavorecidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jcbFavorecidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbFavorecidosMouseClicked(evt);
            }
        });

        btnNovoFavorecido.setText("NOVO");
        btnNovoFavorecido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoFavorecidoActionPerformed(evt);
            }
        });

        tfdDataLancamento.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(48, 48, 48),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(48, 48, 48),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(48, 48, 48),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(48, 48, 48),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    tfdDataLancamento.setFieldFont(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 14));

    tfdDataVencimento.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
                new java.awt.Color(48, 48, 48),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
                new java.awt.Color(48, 48, 48),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
                new java.awt.Color(48, 48, 48),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
                new java.awt.Color(48, 48, 48),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
tfdDataVencimento.setFieldFont(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 14));

tfdDataPagamento.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
    new datechooser.view.appearance.ViewAppearance("custom",
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
            new java.awt.Color(48, 48, 48),
            new java.awt.Color(0, 0, 255),
            false,
            true,
            new datechooser.view.appearance.swing.ButtonPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
            new java.awt.Color(48, 48, 48),
            new java.awt.Color(0, 0, 255),
            true,
            true,
            new datechooser.view.appearance.swing.ButtonPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
            new java.awt.Color(0, 0, 255),
            new java.awt.Color(0, 0, 255),
            false,
            true,
            new datechooser.view.appearance.swing.ButtonPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
            new java.awt.Color(128, 128, 128),
            new java.awt.Color(0, 0, 255),
            false,
            true,
            new datechooser.view.appearance.swing.LabelPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
            new java.awt.Color(48, 48, 48),
            new java.awt.Color(0, 0, 255),
            false,
            true,
            new datechooser.view.appearance.swing.LabelPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 12),
            new java.awt.Color(48, 48, 48),
            new java.awt.Color(255, 0, 0),
            false,
            false,
            new datechooser.view.appearance.swing.ButtonPainter()),
        (datechooser.view.BackRenderer)null,
        false,
        true)));
tfdDataPagamento.setFieldFont(new java.awt.Font("Noto Sans", java.awt.Font.PLAIN, 14));

javax.swing.GroupLayout pFinanceiroLayout = new javax.swing.GroupLayout(pFinanceiro);
pFinanceiro.setLayout(pFinanceiroLayout);
pFinanceiroLayout.setHorizontalGroup(
pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addGroup(pFinanceiroLayout.createSequentialGroup()
    .addGap(29, 29, 29)
    .addComponent(lbDataLancamento2)
    .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pFinanceiroLayout.createSequentialGroup()
            .addGap(39, 39, 39)
            .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pFinanceiroLayout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jCheckJaPago))
                .addGroup(pFinanceiroLayout.createSequentialGroup()
                    .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbDataLancamento1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbDataLancamento))
                        .addComponent(lbValorAtendimento)
                        .addComponent(lbPagoEm))
                    .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pFinanceiroLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(tfdValorAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pFinanceiroLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfdDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfdDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pFinanceiroLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(tfdDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        .addGroup(pFinanceiroLayout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addComponent(jcbFavorecidos, 0, 535, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(btnNovoFavorecido, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
    .addGap(36, 36, 36))
    .addGroup(pFinanceiroLayout.createSequentialGroup()
        .addGap(71, 71, 71)
        .addComponent(lbPaciente)
        .addGap(18, 18, 18)
        .addComponent(lbNomePaciente)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    pFinanceiroLayout.setVerticalGroup(
        pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pFinanceiroLayout.createSequentialGroup()
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(lbPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbNomePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
            .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFinanceiroLayout.createSequentialGroup()
                    .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfdValorAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbValorAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfdDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lbDataLancamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(tfdDataVencimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbDataLancamento2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jcbFavorecidos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnNovoFavorecido, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(28, 28, 28)
            .addComponent(jCheckJaPago)
            .addGap(18, 18, 18)
            .addGroup(pFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbPagoEm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tfdDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(30, 30, 30))
    );

    pCentral.add(pFinanceiro, "Financeiro");

    bg.add(pCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 810, 440));

    btn_Salvar.setBackground(new java.awt.Color(255, 255, 255));
    btn_Salvar.setText("SALVAR");
    btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_SalvarActionPerformed(evt);
        }
    });
    bg.add(btn_Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 90, 30));

    btn_Sair.setBackground(new java.awt.Color(255, 255, 255));
    btn_Sair.setText("SAIR");
    btn_Sair.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_SairActionPerformed(evt);
        }
    });
    bg.add(btn_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, 70, 30));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CloseMouseClicked
        Pai.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CloseMouseClicked

    private void btn_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CloseMouseEntered
        btn_Close.setBackground(new Color(215, 121, 121));
    }//GEN-LAST:event_btn_CloseMouseEntered

    private void btn_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CloseMouseExited
        btn_Close.setBackground(new Color(0,164,137));
    }//GEN-LAST:event_btn_CloseMouseExited

    private void btn_MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MinimizarMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btn_MinimizarMouseClicked

    private void btn_MinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MinimizarMouseEntered
        btn_Minimizar.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btn_MinimizarMouseEntered

    private void btn_MinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MinimizarMouseExited
        btn_Minimizar.setBackground(new Color(0,164,137));
    }//GEN-LAST:event_btn_MinimizarMouseExited

    private void btn_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SairActionPerformed
        Pai.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_SairActionPerformed

    private void jCheckJaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckJaPagoActionPerformed
        DisableCheckButton();
    }//GEN-LAST:event_jCheckJaPagoActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        SalvarConta();
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btnNovoFavorecidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoFavorecidoActionPerformed
        listFavorecido = null;
        listaFavorecidos = null;
        NovoFavorecido favJanela = new NovoFavorecido(this);
        favJanela.setVisible(true);
    }//GEN-LAST:event_btnNovoFavorecidoActionPerformed

    private void jcbFavorecidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbFavorecidosMouseClicked
//        atualizarComboBox();
    }//GEN-LAST:event_jcbFavorecidosMouseClicked

    public void setLabelNomePaciente(){
        
        if(paciente!=null){
            lbNomePaciente.setText(paciente.getNome());
        }
    }
    
    public void atualizarComboBox(){
        FavorecidoRepositorio favRep = new FavorecidoRepositorio();
        
        
        if(listFavorecido==null) {
        	listFavorecido = new ArrayList<Favorecido>();
        	listFavorecido = favRep.recuperarTodasContas();
            
        }
        	listaFavorecidos = new ArrayList<String>();
        	
        for(Favorecido fav : listFavorecido){
            listaFavorecidos.add(fav.getFavorecido());
        }
        
        String [] listFinal = listaFavorecidos.toArray(new String[listaFavorecidos.size()]);
        
        jcbFavorecidos.setModel(new DefaultComboBoxModel<>(listFinal));
        
    }
    
    public void DisableCheckButton(){
        if(!jCheckJaPago.isSelected())
        tfdDataPagamento.setEnabled(false);
        
        if(jCheckJaPago.isSelected()){
        tfdDataPagamento.setEnabled(true);
        }
    }
    
    public boolean validarCampos() {
    	boolean CamposValidos =true;
    	
    	if(tfdValorAtendimento.getText().equals("")||tfdValorAtendimento.getText().contains(" ")) {
    		JOptionPane.showConfirmDialog(null, "Campo em branco ou contém espaços");
    		CamposValidos = false;
    	}
    	
    	if(!tfdValorAtendimento.getText().equals("") || !tfdValorAtendimento.getText().contains(" ")) {
    		
    		try {
    			double Valor = Double.parseDouble(tfdValorAtendimento.getText());
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Formato de Número Inválido para Valor");
                CamposValidos = false;
            }  
    	}
    	
    	if(tfdDataLancamento.getText().equals("  /  /    ")) {
    		CamposValidos = false;
    		JOptionPane.showMessageDialog(null, "Data de Lançamento em Branco");
    	}
    	
    	return CamposValidos;
    }
    
    public Date getData(String tfdData) {
    	
        Date date = new Date();
        SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yy"); 
        try {
		date = formatoData.parse(tfdData);
		} catch (ParseException e) {
		e.printStackTrace();
		}
        
        return date;
    }
    
    public void SalvarConta() {
        
        if(validarCampos()){
            GesMED.bsi.Entidades.ContaPaciente conta = new GesMED.bsi.Entidades.ContaPaciente();
                 
            Date DataLancamento = new Date();
            Date DataVencimento = new Date();
            Date DataPagamento = null;
         
            
            DataLancamento = getData(tfdDataLancamento.getText());
            DataVencimento = getData(tfdDataVencimento.getText());
            if(jCheckJaPago.isSelected()) {
            	DataPagamento = getData(tfdDataPagamento.getText());
            }
            
            conta.setDataLancamento(DataLancamento);
            conta.setDataVencimento(DataVencimento);
            conta.setValor(Double.parseDouble(tfdValorAtendimento.getText()));
            conta.setStatus("Pendente");
            if(DataPagamento!=null) {
            	conta.setDataPago(DataPagamento);
            	conta.setStatus("Pago");
            }
            conta.setFavorecido(listFavorecido.get(jcbFavorecidos.getSelectedIndex()));
            ContaPacienteRepositorio contaRep = new ContaPacienteRepositorio();
            conta.setPaciente(paciente);
            contaRep.atualizar(conta);
            contaRep.encerrar();
          
            fecharJanela();
        }
    	
    }
    
    public void fecharJanela() {
    	Pai.setVisible(true);
    	this.setVisible(false);
    }
    
    public void setColorClicked(JLabel lbButton){
        lbButton.setBackground(new Color(0,204,204));
    }
    
    public void setColorEntered(JLabel lbButton){
        lbButton.setBackground(new Color(200,240,240));
    }
    
    public void setColorExited(JLabel lbButton){
        lbButton.setBackground(new Color(0,204,153));
    }
    
    public void setColorPressed(JLabel lbButton){
        lbButton.setBackground(new Color(140,198,198));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LancarContaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LancarContaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LancarContaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LancarContaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LancarContaPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.ButtonGroup bgFinanceiro;
    private javax.swing.JButton btnNovoFavorecido;
    private javax.swing.JLabel btn_Close;
    private javax.swing.JLabel btn_Maximizar;
    private javax.swing.JLabel btn_Minimizar;
    private javax.swing.JButton btn_Sair;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JLabel imgTituloJanela;
    private javax.swing.JCheckBox jCheckJaPago;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JComboBox<String> jcbFavorecidos;
    private javax.swing.JLabel lbDataLancamento;
    private javax.swing.JLabel lbDataLancamento1;
    private javax.swing.JLabel lbDataLancamento2;
    private javax.swing.JLabel lbIMGAtendimento;
    private javax.swing.JLabel lbNomePaciente;
    private javax.swing.JLabel lbPaciente;
    private javax.swing.JLabel lbPagoEm;
    private javax.swing.JLabel lbValorAtendimento;
    private javax.swing.JPanel pCabecalho;
    private javax.swing.JPanel pCentral;
    private javax.swing.JPanel pFinanceiro;
    private datechooser.beans.DateChooserCombo tfdDataLancamento;
    private datechooser.beans.DateChooserCombo tfdDataPagamento;
    private datechooser.beans.DateChooserCombo tfdDataVencimento;
    private javax.swing.JTextField tfdValorAtendimento;
    // End of variables declaration//GEN-END:variables
}
