/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GesMED.bsi.Interface;

import GesMED.bsi.Entidades.Agendamento;
import GesMED.bsi.Entidades.ListaEsperaAgenda;
import GesMED.bsi.Entidades.Paciente;
import GesMED.bsi.Repositorios.AgendamentoRepositorio;
import GesMED.bsi.Repositorios.PacienteRepositorio;
import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.sun.xml.internal.bind.v2.model.core.ID;

/**
 *
 * @author Leoncio Carioca
 */
public class ListaDeEspera extends javax.swing.JFrame {
    
    private PainelPrincipal Pai;
    private String StatusMenu;
    private Paciente paciente;
    private List<ListaEsperaAgenda> verListEspera;
    private List<ListaEsperaAgenda> listEsperaFinal;
    /**
     * Creates new form AgendarConsulta
     */
    
    public ListaDeEspera() {
        initComponents();
        StatusMenu="AGENDAMENTO";
        setTextFildData();
    }
    public ListaDeEspera(PainelPrincipal Principal) {
        Pai = Principal;
        initComponents();
        StatusMenu="AGENDAMENTO";
        setTextFildData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFinanceiro = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        pCabecalho = new javax.swing.JPanel();
        imgTituloJanela = new javax.swing.JLabel();
        lbIMGListaEspera = new javax.swing.JLabel();
        btn_Close = new javax.swing.JLabel();
        btn_Maximizar = new javax.swing.JLabel();
        btn_Minimizar = new javax.swing.JLabel();
        pCentral = new javax.swing.JPanel();
        lbConvenio = new javax.swing.JLabel();
        jcbConvenio = new javax.swing.JComboBox<>();
        jcbStatus = new javax.swing.JComboBox<>();
        lbStatus = new javax.swing.JLabel();
        lbProcedimento = new javax.swing.JLabel();
        jcbProcedimento = new javax.swing.JComboBox<>();
        lbCPF = new javax.swing.JLabel();
        jspListaEspera = new javax.swing.JScrollPane();
        tblListaEspera = new javax.swing.JTable();
        btn_Adicionar = new javax.swing.JButton();
        tfdCPF = new javax.swing.JFormattedTextField();
        lbNomeCompleto = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        BuscarCPF = new javax.swing.JButton();
        lbStatus1 = new javax.swing.JLabel();
        tfdData = new javax.swing.JFormattedTextField();
        btnVerLista = new javax.swing.JButton();
        btn_AtenderPaciente = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        btn_Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(0, 204, 204));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pCabecalho.setBackground(new java.awt.Color(0, 164, 137));

        imgTituloJanela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufac/bsi/images/Agenda_60px.png"))); // NOI18N
        imgTituloJanela.setText("jLabel2");

        lbIMGListaEspera.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbIMGListaEspera.setForeground(new java.awt.Color(255, 255, 255));
        lbIMGListaEspera.setText("Lista de Espera");

        btn_Close.setBackground(new java.awt.Color(0, 164, 137));
        btn_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufac/bsi/images/Close Window_36px.png"))); // NOI18N
        btn_Close.setOpaque(true);
        btn_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CloseMouseExited(evt);
            }
        });

        btn_Maximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufac/bsi/images/Restore Window_36px.png"))); // NOI18N

        btn_Minimizar.setBackground(new java.awt.Color(0, 164, 137));
        btn_Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufac/bsi/images/Minimize Window_36px.png"))); // NOI18N
        btn_Minimizar.setOpaque(true);
        btn_Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_MinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_MinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_MinimizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pCabecalhoLayout = new javax.swing.GroupLayout(pCabecalho);
        pCabecalho.setLayout(pCabecalhoLayout);
        pCabecalhoLayout.setHorizontalGroup(
            pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCabecalhoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(imgTituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbIMGListaEspera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 653, Short.MAX_VALUE)
                .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Minimizar)
                    .addGroup(pCabecalhoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btn_Maximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(btn_Close))
        );
        pCabecalhoLayout.setVerticalGroup(
            pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCabecalhoLayout.createSequentialGroup()
                .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCabecalhoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imgTituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbIMGListaEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_Minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Maximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        bg.add(pCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 90));

        pCentral.setBackground(new java.awt.Color(255, 255, 255));

        lbConvenio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbConvenio.setText("Convênio:");

        jcbConvenio.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jcbConvenio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Particular" }));

        jcbStatus.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Agendado", "Confirmado", "Chegou", "Em Andamento", " ", " ", " " }));

        lbStatus.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbStatus.setText("Status:");

        lbProcedimento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbProcedimento.setText("Procedimento:");

        jcbProcedimento.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jcbProcedimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Consulta", "Retorno", " " }));

        lbCPF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbCPF.setText("CPF:");

        tblListaEspera.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        tblListaEspera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ord", "Nome", "Status", "Procedimento", "Convênio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListaEspera.setRowHeight(22);
        jspListaEspera.setViewportView(tblListaEspera);
        if (tblListaEspera.getColumnModel().getColumnCount() > 0) {
            tblListaEspera.getColumnModel().getColumn(0).setMinWidth(30);
            tblListaEspera.getColumnModel().getColumn(0).setMaxWidth(35);
            tblListaEspera.getColumnModel().getColumn(1).setMinWidth(400);
            tblListaEspera.getColumnModel().getColumn(1).setPreferredWidth(400);
            tblListaEspera.getColumnModel().getColumn(1).setMaxWidth(450);
            tblListaEspera.getColumnModel().getColumn(4).setMinWidth(150);
            tblListaEspera.getColumnModel().getColumn(4).setPreferredWidth(150);
            tblListaEspera.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        btn_Adicionar.setBackground(new java.awt.Color(255, 255, 255));
        btn_Adicionar.setText("ADICIONAR");
        btn_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdicionarActionPerformed(evt);
            }
        });

        try {
            tfdCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfdCPF.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N

        lbNomeCompleto.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbNomeCompleto.setText("|");

        lbNome.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbNome.setText("Nome:");

        BuscarCPF.setText("Buscar");
        BuscarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCPFActionPerformed(evt);
            }
        });

        lbStatus1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbStatus1.setText("Data:");

        try {
            tfdData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfdData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfdData.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N

        btnVerLista.setText("VER");
        btnVerLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerListaActionPerformed(evt);
            }
        });

        btn_AtenderPaciente.setBackground(new java.awt.Color(255, 255, 255));
        btn_AtenderPaciente.setText("INICIAR ATENDIMENTO");
        btn_AtenderPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtenderPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCentralLayout = new javax.swing.GroupLayout(pCentral);
        pCentral.setLayout(pCentralLayout);
        pCentralLayout.setHorizontalGroup(
            pCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCentralLayout.createSequentialGroup()
                        .addComponent(jspListaEspera)
                        .addContainerGap())
                    .addGroup(pCentralLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(pCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pCentralLayout.createSequentialGroup()
                                .addComponent(lbStatus1)
                                .addGap(18, 18, 18)
                                .addComponent(tfdData, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(pCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pCentralLayout.createSequentialGroup()
                                        .addComponent(lbConvenio)
                                        .addGap(18, 18, 18)
                                        .addGroup(pCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pCentralLayout.createSequentialGroup()
                                        .addComponent(btnVerLista, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbStatus)
                                        .addGap(210, 210, 210)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbProcedimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))
                            .addGroup(pCentralLayout.createSequentialGroup()
                                .addComponent(lbCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfdCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BuscarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbNome)
                                .addGap(18, 18, 18)
                                .addComponent(lbNomeCompleto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))))))
            .addGroup(pCentralLayout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(btn_AtenderPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pCentralLayout.setVerticalGroup(
            pCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStatus)
                    .addComponent(jcbStatus)
                    .addComponent(lbProcedimento)
                    .addComponent(jcbProcedimento)
                    .addComponent(lbStatus1)
                    .addComponent(tfdData, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerLista, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConvenio)
                    .addComponent(jcbConvenio))
                .addGap(28, 28, 28)
                .addGroup(pCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfdCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BuscarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspListaEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_AtenderPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        bg.add(pCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1000, 470));

        btn_Salvar.setBackground(new java.awt.Color(255, 255, 255));
        btn_Salvar.setText("SALVAR");
        bg.add(btn_Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 80, 30));

        btn_Sair.setBackground(new java.awt.Color(255, 255, 255));
        btn_Sair.setText("SAIR");
        btn_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SairActionPerformed(evt);
            }
        });
        bg.add(btn_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CloseMouseClicked
        Pai.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CloseMouseClicked

    private void btn_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CloseMouseEntered
        btn_Close.setBackground(new Color(215, 121, 121));
    }//GEN-LAST:event_btn_CloseMouseEntered

    private void btn_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CloseMouseExited
        btn_Close.setBackground(new Color(0,164,137));
    }//GEN-LAST:event_btn_CloseMouseExited

    private void btn_MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MinimizarMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btn_MinimizarMouseClicked

    private void btn_MinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MinimizarMouseEntered
        btn_Minimizar.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btn_MinimizarMouseEntered

    private void btn_MinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MinimizarMouseExited
        btn_Minimizar.setBackground(new Color(0,164,137));
    }//GEN-LAST:event_btn_MinimizarMouseExited

    private void btn_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SairActionPerformed
        Pai.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_SairActionPerformed

    private void BuscarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCPFActionPerformed
     buscaPorCPF();
//     for( boolean status : OperacoesList){
//         JOptionPane.showMessageDialog(null, "Status: "+ status);
//     }
    }//GEN-LAST:event_BuscarCPFActionPerformed

    private void btnVerListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerListaActionPerformed
        listAgendaForData();
        if(verListEspera!=null){
            PreviewListaEspera previewList = new PreviewListaEspera(verListEspera, this, 0); // O ZERO É PARA IDENTIFICAR A JANELA QUE É SÓ PARA VER A LISTA DO DIA
            previewList.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Data não Preenchida");
        }
        
    }//GEN-LAST:event_btnVerListaActionPerformed

    private void btn_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdicionarActionPerformed
        
    	AgendamentoRepositorio agenRep = new AgendamentoRepositorio();

    	
        List<Agendamento> listTempAdicionar = new ArrayList<Agendamento>();
        
        if(!jcbStatus.getSelectedItem().equals("Selecione")&&!jcbProcedimento.getSelectedItem().equals("Selecione")&&!jcbConvenio.getSelectedItem().equals("Selecione")) {
        	 //TODAS MARCADAS = STATUS + PROCEDIMENTO + CONVENIO
        	
        	listTempAdicionar = agenRep.listarPorSPC(jcbStatus.getSelectedItem().toString(),jcbProcedimento.getSelectedItem().toString(),jcbStatus.getSelectedItem().toString());
        	
        }else if(!jcbStatus.getSelectedItem().equals("Selecione")&&!jcbProcedimento.getSelectedItem().equals("Selecione")&&jcbConvenio.getSelectedItem().equals("Selecione")) {
        	//APENAS STATUS E PROCEDIMENTO
        	listTempAdicionar = agenRep.listarPorStatusProcedimento(jcbStatus.getSelectedItem().toString(), jcbProcedimento.getSelectedItem().toString());
        	
        }else if(!jcbStatus.getSelectedItem().equals("Selecione")
        		&&jcbProcedimento.getSelectedItem().equals("Selecione")
        		&&jcbConvenio.getSelectedItem().equals("Selecione")) {
        	//APENAS STATUS
        		listTempAdicionar = agenRep.listarPorStatus(jcbStatus.getSelectedItem().toString());
        }else if(jcbStatus.getSelectedItem().equals("Selecione")
        		&&!jcbProcedimento.getSelectedItem().equals("Selecione")
        		&&!jcbConvenio.getSelectedItem().equals("Selecione")) {
        	//APENAS PROCEDIMENTO + CONVENIO
        	listTempAdicionar = agenRep.listarPorProcedimentoConvenio(jcbProcedimento.getSelectedItem().toString(), jcbConvenio.getSelectedItem().toString());
        	
        }else if(jcbStatus.getSelectedItem().equals("Selecione")
        		&&!jcbProcedimento.getSelectedItem().equals("Selecione")
        		&&jcbConvenio.getSelectedItem().equals("Selecione")) {
        	//APENAS PROCEDIMENTO
        	listTempAdicionar = agenRep.listarPorProcedimento(jcbProcedimento.getSelectedItem().toString());
        	
        }else if(!jcbStatus.getSelectedItem().equals("Selecione")
        		&&jcbProcedimento.getSelectedItem().equals("Selecione")
        		&&!jcbConvenio.getSelectedItem().equals("Selecione")) {
        	//APENAS STATUS E CONVENIO
        	listTempAdicionar = agenRep.listarPorConventio(jcbConvenio.getSelectedItem().toString());
        	
        }else if(jcbStatus.getSelectedItem().equals("Selecione")
        		&&!jcbProcedimento.getSelectedItem().equals("Selecione")
        		&&jcbConvenio.getSelectedItem().equals("Selecione")) {
        	//APENAS PROCEDIMENTO
        	listTempAdicionar = agenRep.listarPorProcedimento(jcbProcedimento.getSelectedItem().toString());
        }
        
        if(jcbStatus.getSelectedItem().equals("Selecione")&&jcbProcedimento.getSelectedItem().equals("Selecione")&&jcbConvenio.getSelectedItem().equals("Selecione")) {
        		if(tfdData.getText().contains(" ")) {
        		JOptionPane.showMessageDialog(null, "O Campo Data está Vazio ou Formato Inválido, e nada foi Selecionado nos outros Campos");
        		setTextFildData();
        		}else {
        			listAgendaForData();
            	    if(verListEspera!=null){
            	    PreviewListaEspera previewList = new PreviewListaEspera(verListEspera, this, 1); // O ZERO É PARA IDENTIFICAR A JANELA QUE É SÓ PARA VER A LISTA DO DIA
            	    previewList.setVisible(true);                                                   // 1 - UM É PARA IDENTIFICAR A JANELA QUE VAMOS ADICIONAR A LISTA
            	    this.setVisible(false);
            	   }else {
            		   JOptionPane.showMessageDialog(null, "Esta mesma Operação já foi Confirmada antes e adicionada na Lista");
            	   }
        		}
        }else if(listTempAdicionar!=null&&listTempAdicionar.size()!=0) {
              		
           	PreviewListaEspera viewListEsp = new PreviewListaEspera(prepararListaEspera(listTempAdicionar),this,1);
            	viewListEsp.setVisible(true);
            	this.setVisible(false);
        	        	
        }else{
            if(listTempAdicionar.size()==0)
            JOptionPane.showMessageDialog(null, "Não há Consultas para este Perfil Selecionado");
        }
        agenRep.encerrar();
        
    }//GEN-LAST:event_btn_AdicionarActionPerformed

    private void btn_AtenderPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtenderPacienteActionPerformed
         iniciarAtendimento();
    }//GEN-LAST:event_btn_AtenderPacienteActionPerformed

 
    
    public void buscaPorCPF() {
    	
    	PacienteRepositorio pr = new PacienteRepositorio();
        List<Paciente> BuscaPaciente = pr.recuperarPacienteCPF(tfdCPF.getText());
      	pr.encerrar();
      	if(BuscaPaciente.size()==1) {
      		paciente = BuscaPaciente.get(0);
      		String Nome = paciente.getNome();
          	lbNomeCompleto.setText(Nome);
      	}else {
      		JOptionPane.showMessageDialog(null, "CPF Não encontrado!");
      	}
    }
    
    
    public void setTextFildData(){
            LocalDate data = LocalDate.now();
            String Datastr = data.toString();
            String[] strTemp = Datastr.split("-");
            Datastr = strTemp[0]+strTemp[1]+strTemp[2];
                     
            tfdData.setText(Datastr);
        
    }
    
    public void setListEspera(List<ListaEsperaAgenda> listEsperaTemp){
        if(listEsperaFinal==null){
            listEsperaFinal =listEsperaTemp;
            CarregarTabela();
        }else{
        for(ListaEsperaAgenda listEspAg : listEsperaTemp){
            listEsperaFinal.add(listEspAg);
            CarregarTabela();
        }
      }      
    }
    
       public void CarregarTabela(){
        
        DefaultTableModel modelListEspera = (DefaultTableModel) tblListaEspera.getModel();
        modelListEspera.setNumRows(0);
        
        for(ListaEsperaAgenda listEsp : listEsperaFinal){
            
            modelListEspera.addRow(new Object[]{
            listEsperaFinal.indexOf(listEsp), listEsp.getNome(), listEsp.getStatus(), listEsp.getProcedimento(), listEsp.getConvenio()
            });
            
        }
        
    }
    
      public void listAgendaForData(){
    	  String Datastr="";
            if(tfdData.getText().contains(" ")){
                JOptionPane.showMessageDialog(null, "Formato de Data Inválido");
            }else {
            	Datastr = tfdData.getText();
            }
            
            String[] strTemp = Datastr.split("/");
            Datastr = strTemp[0]+"-"+strTemp[1]+"-"+strTemp[2];
                     
            List<Agendamento> listAgenda = new ArrayList<Agendamento>();
            
            AgendamentoRepositorio agenRep = new AgendamentoRepositorio();
            
            listAgenda= agenRep.listarPorData(Datastr);
            
            ListaEsperaAgenda listEsp = new ListaEsperaAgenda();
            verListEspera = new ArrayList<ListaEsperaAgenda>();
            for(Agendamento agendamento : listAgenda) {
            	listEsp.setID(agendamento.getPaciente().getID());
                listEsp.setIDAgendamento(agendamento.getIDAgenda());
            	listEsp.setNome(agendamento.getPaciente().getNome());
            	listEsp.setCelular(agendamento.getPaciente().getTelefone().getTelefone());
            	listEsp.setCPF(agendamento.getPaciente().getCPF());
            	listEsp.setStatus(agendamento.getStatus());
            	listEsp.setProcedimento(agendamento.getProcedimento());
            	listEsp.setConvenio(agendamento.getConvenio());
            	verListEspera.add(listEsp);
	        }
	    }
      
      public void iniciarAtendimento(){
    	  
    	  int IDListEsspera = (int) tblListaEspera.getSelectedRow();
    	  ListaEsperaAgenda espera = listEsperaFinal.get(IDListEsspera);
          AgendamentoRepositorio agenRep = new AgendamentoRepositorio();
          
          Agendamento agenda = agenRep.recuperar(espera.getIDAgendamento());
          agenRep.encerrar();

    	  
          if(agenda!=null){
          AtendimentoConsulta atender = new AtendimentoConsulta(this, agenda);
          atender.setVisible(true);
          this.setVisible(false);
          }
          
      }
      
      
      public List<ListaEsperaAgenda> prepararListaEspera(List<Agendamento> listAdicionar){
      		
      		     		
      		List<Agendamento> listAgenda = new ArrayList<Agendamento>();
            
            AgendamentoRepositorio agenRep = new AgendamentoRepositorio();
            
            listAgenda = listAdicionar;
            
            ListaEsperaAgenda listEsp = new ListaEsperaAgenda();
            verListEspera = new ArrayList<ListaEsperaAgenda>();
            for(Agendamento agendamento : listAgenda) {
            	listEsp.setID(agendamento.getPaciente().getID());
                listEsp.setIDAgendamento(agendamento.getIDAgenda());
            	listEsp.setNome(agendamento.getPaciente().getNome());
            	listEsp.setCelular(agendamento.getPaciente().getTelefone().getTelefone());
            	listEsp.setCPF(agendamento.getPaciente().getCPF());
            	listEsp.setStatus(agendamento.getStatus());
            	listEsp.setProcedimento(agendamento.getProcedimento());
            	listEsp.setConvenio(agendamento.getConvenio());
            	verListEspera.add(listEsp);
	        }
      		
      		return verListEspera;
      	}
           
 
	    public void setColorClicked(JLabel lbButton){
	        lbButton.setBackground(new Color(0,204,204));
	    }
	    
	    public void setColorEntered(JLabel lbButton){
	        lbButton.setBackground(new Color(200,240,240));
	    }
	    
	    public void setColorExited(JLabel lbButton){
	        lbButton.setBackground(new Color(0,204,153));
	    }
	    
	    public void setColorPressed(JLabel lbButton){
	        lbButton.setBackground(new Color(140,198,198));
	    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaDeEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaDeEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaDeEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaDeEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaDeEspera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarCPF;
    private javax.swing.JPanel bg;
    private javax.swing.ButtonGroup bgFinanceiro;
    private javax.swing.JButton btnVerLista;
    private javax.swing.JButton btn_Adicionar;
    private javax.swing.JButton btn_AtenderPaciente;
    private javax.swing.JLabel btn_Close;
    private javax.swing.JLabel btn_Maximizar;
    private javax.swing.JLabel btn_Minimizar;
    private javax.swing.JButton btn_Sair;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JLabel imgTituloJanela;
    private javax.swing.JComboBox<String> jcbConvenio;
    private javax.swing.JComboBox<String> jcbProcedimento;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JScrollPane jspListaEspera;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbConvenio;
    private javax.swing.JLabel lbIMGListaEspera;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNomeCompleto;
    private javax.swing.JLabel lbProcedimento;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbStatus1;
    private javax.swing.JPanel pCabecalho;
    private javax.swing.JPanel pCentral;
    private javax.swing.JTable tblListaEspera;
    private javax.swing.JFormattedTextField tfdCPF;
    private javax.swing.JFormattedTextField tfdData;
    // End of variables declaration//GEN-END:variables
}
