/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GesMED.bsi.Interface;

import GesMED.bsi.Entidades.ListaEsperaAgenda;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leoncio
 */
public class PreviewListaEspera extends javax.swing.JFrame {

    
    
    /**
     * Creates new form ViewListaEspera
     */
    private List<ListaEsperaAgenda> listEspera;
    private ListaDeEspera Pai;
    private int Operacao = -1;
    
    
    
    public PreviewListaEspera() {
        initComponents();
    }
    
    public PreviewListaEspera(List<ListaEsperaAgenda> lista, ListaDeEspera Painel, int Tipo) {
        initComponents();
        Pai = Painel;
        this.listEspera = lista;
        Operacao = Tipo;
        CarregarTabela();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        PainelCabecalho = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PainelTabelaList = new javax.swing.JPanel();
        scpListaEspera = new javax.swing.JScrollPane();
        tblListaEspera = new javax.swing.JTable();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        setResizable(false);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelCabecalho.setBackground(new java.awt.Color(0, 164, 137));

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 28)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Previsão da Ordem Selecionada");

        javax.swing.GroupLayout PainelCabecalhoLayout = new javax.swing.GroupLayout(PainelCabecalho);
        PainelCabecalho.setLayout(PainelCabecalhoLayout);
        PainelCabecalhoLayout.setHorizontalGroup(
            PainelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCabecalhoLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel1)
                .addContainerGap(337, Short.MAX_VALUE))
        );
        PainelCabecalhoLayout.setVerticalGroup(
            PainelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCabecalhoLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32))
        );

        bg.add(PainelCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        PainelTabelaList.setBackground(java.awt.Color.white);

        tblListaEspera.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        tblListaEspera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ORD", "NOME", "STATUS", "PROCEDIMENTO", "CONVENIO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblListaEspera.setRowHeight(22);
        scpListaEspera.setViewportView(tblListaEspera);
        if (tblListaEspera.getColumnModel().getColumnCount() > 0) {
            tblListaEspera.getColumnModel().getColumn(0).setMinWidth(45);
            tblListaEspera.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblListaEspera.getColumnModel().getColumn(0).setMaxWidth(50);
            tblListaEspera.getColumnModel().getColumn(1).setMinWidth(350);
            tblListaEspera.getColumnModel().getColumn(1).setPreferredWidth(400);
            tblListaEspera.getColumnModel().getColumn(1).setMaxWidth(400);
            tblListaEspera.getColumnModel().getColumn(2).setMinWidth(150);
            tblListaEspera.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblListaEspera.getColumnModel().getColumn(2).setMaxWidth(200);
            tblListaEspera.getColumnModel().getColumn(3).setMinWidth(150);
            tblListaEspera.getColumnModel().getColumn(3).setPreferredWidth(150);
            tblListaEspera.getColumnModel().getColumn(3).setMaxWidth(200);
            tblListaEspera.getColumnModel().getColumn(4).setMinWidth(150);
            tblListaEspera.getColumnModel().getColumn(4).setPreferredWidth(150);
            tblListaEspera.getColumnModel().getColumn(4).setMaxWidth(200);
        }

        javax.swing.GroupLayout PainelTabelaListLayout = new javax.swing.GroupLayout(PainelTabelaList);
        PainelTabelaList.setLayout(PainelTabelaListLayout);
        PainelTabelaListLayout.setHorizontalGroup(
            PainelTabelaListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTabelaListLayout.createSequentialGroup()
                .addComponent(scpListaEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PainelTabelaListLayout.setVerticalGroup(
            PainelTabelaListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelTabelaListLayout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(scpListaEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(PainelTabelaList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 340));

        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        bg.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 120, 40));

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        bg.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if(Operacao==-1){
            this.dispose();
        }else if(Operacao==0){
        this.setVisible(false);
        Pai.setVisible(true);   
        }else if(Operacao==1){
        this.setVisible(false);
        Pai.setListEspera(listEspera);
        Pai.setVisible(true);
        
        }
        
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if(Operacao==0||Operacao==1){
        this.setVisible(false);
        Pai.setVisible(true);  
        }else{
        this.dispose();
        }
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    public void CarregarTabela(){
        
        DefaultTableModel modelListEspera = (DefaultTableModel) tblListaEspera.getModel();
        modelListEspera.setNumRows(0);
        for(ListaEsperaAgenda listEsp : listEspera){
            modelListEspera.addRow(new Object[]{
            listEsp.getID(), listEsp.getNome(), listEsp.getStatus(), listEsp.getProcedimento(), listEsp.getConvenio()
            });
            
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreviewListaEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreviewListaEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreviewListaEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreviewListaEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreviewListaEspera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelCabecalho;
    private javax.swing.JPanel PainelTabelaList;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane scpListaEspera;
    private javax.swing.JTable tblListaEspera;
    // End of variables declaration//GEN-END:variables
}
